package kz.hrms.splitupauth.entity;

public enum AdminActionType {
    ACCESS_CONFIRMED,
    ACCESS_REJECTED,
    ROOM_BLOCKED,
    USER_BANNED,
    USER_UNBANNED,
    USER_CREATED,
    USER_ROLE_CHANGED,
    REFUND_INITIATED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    DISPUTE_RESOLVED,
    BATCH_CONFIRM,
    OWNER_VERIFICATION_CHANGED
}
