package kz.hrms.splitupauth.entity;

public enum IdentifierRevealReasonCode {
  PROVIDE_SERVICE_ACCESS,
  RETRY_SERVICE_INVITE,
  RESOLVE_ACCESS_CONFIGURATION,
  SUPPORT_TICKET,
  DISPUTE_INVESTIGATION,
  MODERATION_REVIEW,
  FRAUD_REVIEW,
  ACCESS_ISSUE
}
