ALTER TABLE news ADD COLUMN IF NOT EXISTS image_key_kz VARCHAR(255);
ALTER TABLE news ADD COLUMN IF NOT EXISTS image_key_ru VARCHAR(255);
ALTER TABLE news ADD COLUMN IF NOT EXISTS image_key_en VARCHAR(255);

ALTER TABLE stories ADD COLUMN IF NOT EXISTS image_key_kz VARCHAR(255);
ALTER TABLE stories ADD COLUMN IF NOT EXISTS image_key_ru VARCHAR(255);
ALTER TABLE stories ADD COLUMN IF NOT EXISTS image_key_en VARCHAR(255);
