ALTER TABLE users ADD COLUMN ban_starts_at TIMESTAMP;
ALTER TABLE users ADD COLUMN ban_until TIMESTAMP;
UPDATE users SET ban_starts_at = COALESCE(banned_at, CURRENT_TIMESTAMP) WHERE status = 'BANNED';
CREATE INDEX idx_users_ban_activation ON users(ban_starts_at) WHERE status = 'ACTIVE' AND ban_starts_at IS NOT NULL;
CREATE INDEX idx_users_ban_expiration ON users(ban_until) WHERE status = 'BANNED' AND ban_until IS NOT NULL;

ALTER TABLE admin_action_log DROP CONSTRAINT IF EXISTS chk_admin_action_log_action_type;
ALTER TABLE admin_action_log ADD CONSTRAINT chk_admin_action_log_action_type CHECK (action_type IN (
    'ACCESS_CONFIRMED', 'ACCESS_REJECTED', 'ROOM_BLOCKED', 'ROOM_UNBLOCKED',
    'USER_BANNED', 'USER_UNBANNED', 'USER_CREATED', 'USER_ROLE_CHANGED',
    'REFUND_INITIATED', 'REFUND_APPROVED', 'REFUND_REJECTED', 'DISPUTE_RESOLVED',
    'BATCH_CONFIRM', 'OWNER_VERIFICATION_CHANGED', 'CATEGORY_CREATED', 'CATEGORY_UPDATED',
    'CATEGORY_DELETED', 'SERVICE_CREATED', 'SERVICE_UPDATED', 'SERVICE_DELETED',
    'TARIFF_CREATED', 'TARIFF_UPDATED', 'TARIFF_DELETED', 'TESTIMONIAL_FEATURED',
    'TESTIMONIAL_UNFEATURED', 'TESTIMONIAL_REORDERED', 'TESTIMONIAL_EDITED',
    'TESTIMONIAL_DELETED', 'SITE_CONTENT_UPDATED', 'FEEDBACK_STATUS_CHANGED',
    'FEEDBACK_NOTE_UPDATED', 'NEWS_CREATED', 'NEWS_UPDATED', 'NEWS_DELETED',
    'LEGAL_DOCUMENT_UPDATED', 'STORY_CREATED', 'STORY_UPDATED', 'STORY_DELETED',
    'USER_DELETED_IDENTIFIERS_REVEALED', 'USER_REPORT_ASSIGNED',
    'USER_REPORT_STATUS_CHANGED', 'USER_RESTRICTION_SCHEDULED',
    'USER_RESTRICTION_ACTIVATED', 'USER_RESTRICTION_EXPIRED'
));
